### ISSUE TITLE
Is WETH fallback safe?

### ISSUE THREAD

**Issue by nnnnicholas** [austintgriffith/banana-auction#1]
When a new bid is successfully placed, the prior highest bid must be immediately refunded to the prior highest bidder. 

We are currently using an approach @austintgriffith borrowed from @w1nt3r-eth. First, the contract attempts to send ETH. If that fails, the ETH is deposited in the WETH contract and transferred. 

<img width="579" alt="image" src="https://user-images.githubusercontent.com/1418561/178380915-c2d5473b-96e4-4d6b-83c8-413938fa1a80.png">

Is this method foolproof? Can it be griefed? @viraj124

**Comment by nnnnicholas** [comment]
If there _is_ any way the WETH transfer could fail, we could replace the `require` on line 83 with an `emergencyWithdrawlAmount` that could be withdrawn via an onlyOwner `emergencyWithdraw` fn 
<img width="548" alt="image" src="https://user-images.githubusercontent.com/1418561/178381435-9f25fb00-1943-4425-85bd-2de3daef0e95.png">

**Comment by viraj124** [comment]
@nnnnicholas having a look at this soon & will push some changes

**Comment by viraj124** [comment]
a balance of check would be nice pushing some updates in a pr

**Comment by viraj124** [comment]
> If there _is_ any way the WETH transfer could fail, we could replace the `require` on line 83 with an `emergencyWithdrawlAmount` that could be withdrawn via an onlyOwner `emergencyWithdraw` fn <img alt="image" width="548" src="https://user-images.githubusercontent.com/1418561/178381435-9f25fb00-1943-4425-85bd-2de3daef0e95.png">

@nnnnicholas this will only fail due to low balance but there is a re-entrancy check missing which is the caveat with call adding that too in a pr

**Comment by viraj124** [comment]
@nnnnicholas @austintgriffith regarding this if block there was a vulnerability around re-entrancy so have fixed that in this pr  https://github.com/austintgriffith/banana-auction/pull/2 so IMO this piece of code is sort of optional because eth transfer going forward will only fail because of low balance what do you guys think ?
```
            if (!sent) {
                weth.deposit{value: lastAmount}();
                require(
                    weth.transfer(lastBidder, lastAmount),
                    "Payment failed"
                );
            }
```

**Comment by nnnnicholas** [comment]
@viraj124 what if the the bidder is a contract with a non-payable fallback fn? would the ETH call not fail?

**Comment by viraj124** [comment]
@nnnnicholas if the bidder is a contract without a fallback/receive yeah then it will fail missed that, yeah better to have this if block

**Comment by nnnnicholas** [comment]
Great, thanks @viraj124. Will leave it in then.
